/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: "category",
      label: "Backend",
      items: [{ type: "autogenerated", dirName: "backend" }],
    },
    {
      type: "category",
      label: "Web",
      items: [{ type: "autogenerated", dirName: "web" }],
    },
    {
      type: "category",
      label: "Mobile",
      items: [{ type: "autogenerated", dirName: "mobile" }],
    },
    {
      type: "category",
      label: "Engine",
      items: [{ type: "autogenerated", dirName: "engine" }],
    },
    {
      type: "category",
      label: "Deployment",
      items: [{ type: "autogenerated", dirName: "deployment" }],
    },
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
  ],
};

export default sidebars;