/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'generated-index',
        title: 'Architecture',
        description: 'Repository architecture, environment model, release strategy, and documentation governance.',
      },
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: 'Repositories',
      link: {
        type: 'generated-index',
        title: 'Repositories',
        description: 'Repository-level responsibilities, boundaries, and local documentation expectations.',
      },
      items: [{ type: 'autogenerated', dirName: 'repositories' }],
    },
    {
      type: 'category',
      label: 'Contribution',
      link: {
        type: 'generated-index',
        title: 'Contribution',
        description: 'Workflow, branch and commit standards, review expectations, and governance files.',
      },
      items: [{ type: 'autogenerated', dirName: 'contribution' }],
    },
    {
      type: 'category',
      label: 'Workflows',
      link: {
        type: 'generated-index',
        title: 'Workflows',
        description: 'CI, semantic tagging, documentation sync, and release flow.',
      },
      items: [{ type: 'autogenerated', dirName: 'workflows' }],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {
        type: 'generated-index',
        title: 'Operations',
        description: 'Deployment orchestration, environment rules, and promotion procedures.',
      },
      items: [{ type: 'autogenerated', dirName: 'operations' }],
    },
    {
      type: 'category',
      label: 'Standards',
      link: {
        type: 'generated-index',
        title: 'Standards',
        description: 'Shared terminology and architecture decision record process.',
      },
      items: [{ type: 'autogenerated', dirName: 'standards' }],
    },
  ],
};

export default sidebars;
